### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by eByte23** [dawsonsuen/LMS2#1]
- [ ] Implement [LiteDb](https://github.com/mbdavid/LiteDB) as EventStore
- [ ] Start moving EF ReadModels to EventStore based
- [ ] Implement ReadModels using [json-flatfile-datastore](https://github.com/ttu/json-flatfile-datastore)
